-- A "plan to reassign a state's shipping location on a future date," used by
-- the Growth & Distribution tab's reassignment planner. Deliberately
-- separate from state_location_routing (the CURRENT assignment): adding a
-- plan here only reshapes forward-looking estimates (distribution %,
-- bouquets received, turnaround) via src/app/api/distribution-estimate — it
-- does not change what state_location_routing says is true today. Making a
-- plan "official" is still a separate, manual toggle in the State Routing
-- list, so a plan you forgot about can't silently change what the rest of
-- the app treats as the live routing.
create table planned_state_moves (
  id             bigint generated by default as identity primary key,
  state_code     text not null,
  new_location   text not null check (new_location in ('Utah', 'Georgia')),
  effective_date date not null,
  note           text,
  created_by     text,
  created_at     timestamptz not null default now()
);

create index planned_state_moves_state_idx on planned_state_moves (state_code, effective_date);
