-- Effective-dated pay rate history, so a rate change has a recorded date and
-- past weeks that estimate cost from a rate (no actual payroll on file) can
-- look up what the rate was AT THAT TIME instead of whatever it is today.
-- Append-only — never update/delete a row, only add new ones. Mirrors the
-- from/to-dated convention in src/lib/managers.ts, adapted to a real table
-- since rates change routinely via upload rather than being a handful of
-- hand-maintained manager transitions.
create table employee_rate_history (
  id            bigint generated by default as identity primary key,
  full_name     text not null,
  location      text not null,
  department    text not null,
  pay_type      text not null check (pay_type in ('hourly', 'salary')),
  hourly_rate   numeric not null default 0,
  annual_salary numeric not null default 0,
  effective_date date not null,
  source        text not null default 'upload',
  created_at    timestamptz not null default now()
);

create index employee_rate_history_lookup_idx
  on employee_rate_history (full_name, location, department, effective_date desc);

-- Genesis backfill: one row per employee currently on file, dated far enough
-- back to cover every tracked historical week. We have no record of rates
-- before this migration, so this is the honest earliest-known value applied
-- to all prior weeks rather than leaving those lookups empty.
insert into employee_rate_history (full_name, location, department, pay_type, hourly_rate, annual_salary, effective_date, source)
select full_name, location, department, pay_type, hourly_rate, annual_salary, date '2000-01-01', 'backfill'
from rippling_employees
where active = true;
