-- Monthly performance bonuses, from Rippling's separate "Bonus payroll
-- report" export (not the weekly wages report). Paid ~monthly but 3-4 weeks
-- after the month they're earned for (e.g. July bonuses land in late
-- August) -- bonus_month is the EARNED month, parsed from the report's
-- "Pay run name" column (e.g. "2026 July Bonuses" -> 2026-07-01);
-- check_date is when it was actually paid. Only the Monthly CPO view's
-- "Incl. Bonus" toggle reads this table -- see src/app/api/kpis/route.ts.
--
-- Unlike GM cost (location-wide only), bonuses are per-employee and so CAN
-- be attributed to a department/location, via a name match against
-- rippling_employees done at upload time. location/department stay
-- nullable because the bonus report itself has no such columns -- a row
-- whose employee name doesn't cleanly match the directory is still stored
-- (never silently dropped) with both null, reported back to the uploading
-- admin, and excluded from department-level KPI totals until reconciled.
--
-- The dedup key deliberately excludes location/department: they're
-- enrichment, not identity, so re-uploading after fixing a name mismatch
-- in the Employee Directory correctly updates the existing row instead of
-- duplicating it or leaving it unmatched forever.
create table monthly_bonus (
  id            bigint generated by default as identity primary key,
  employee      text not null,
  location      text,
  department    text,
  bonus_month   date not null,
  gross_pay     numeric not null,
  check_date    date not null,
  pay_run_name  text not null,
  uploaded_at   timestamptz not null default now(),
  unique (employee, bonus_month, check_date, pay_run_name)
);

create index monthly_bonus_lookup_idx
  on monthly_bonus (location, department, bonus_month);
