-- Real-time design production events, pushed by the Pressed Floral app's own
-- webhook the moment an order product leaves "Ready to Frame" for the first
-- time (that's when PF auto-assigns the designer). Lets Design actuals in
-- team_member_week_actuals update the same day instead of waiting on the
-- Monday sync-production-actuals cron's heuristic scan of PF order history.
--
-- order_product_key is unique so a retried webhook call, or an order that
-- somehow re-enters/exits Ready to Frame again, only ever counts once — the
-- first exit wins, matching "count it the moment it's first assigned."
create table design_completions (
  id                 bigint generated by default as identity primary key,
  order_num          text not null,
  order_product_key  text not null unique,
  variant_title      text,
  designer_uuid      text,
  designer_name      text,
  location           text,
  from_status        text not null default 'readyToFrame',
  to_status           text not null,
  changed_at         timestamptz not null,
  week_of            date not null,
  created_at         timestamptz not null default now()
);

create index design_completions_location_week_idx
  on design_completions (location, week_of, designer_name);
